spring:
    data:
        mongodb:
            uri: mongodb://mongodb:mongodbpw@mongo:27017/?readPreference=primary
            database: qushift
    security:
        oauth2:
            resource-server:
                opaque-token:
                    introspection-uri: http://go-qushift-auth-service:5000/api/v1/auth/verify
                    client-id: QSHIFT_API_SECRET
                    client-secret: ofBYMfWcT48VYenq8kh0jzdYegxxSPAZ

client:
    frontend-endpoint: http://nextjs-qushift-frontend:4000